"""add drivers table

Revision ID: 3302894ff3bb
Revises: 81e86c390aa9
Create Date: 2025-08-28 07:52:24.603865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3302894ff3bb'
down_revision: Union[str, None] = '81e86c390aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_truck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    # ### end Alembic commands ###
